# Generated by Django 4.0.1 on 2022-04-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='software',
            field=models.ManyToManyField(to='mainapp.Software'),
        ),
    ]
