# Generated by Django 4.0.1 on 2022-04-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='midle_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
    ]
